# deep-apiserver 全配置

# RESTful 服务配置
server:
    mode: debug # server mode: release, debug, test，默认 release
    healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由，默认 true
    middlewares:
    max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3
